version: "3"
services:
  middle:
    build: ./middle/
    volumes:
      - ./middle/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend/
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
