version: "3"
services:
  middle:
    build:
      context: ./middle
      dockerfile: Dockerfile.dev
    volumes:
      - ./middle/src:/home/ubuntu/middle/src
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/home/ubuntu/backend/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3006:3006
    volumes:
      - ./frontend/src:/home/ubuntu/frontend/src
      - ./frontend/public:/home/ubuntu/frontend/public
    environment:
      - NODE_ENV=development
