version: "3"
services:
  middle:
    build: ./middle/
    volumes:
      - ./middle/app
      - /app/node_modules

  backend:
    build: ./backend/
    ports:
      - 3000:3000
    volumes:
      - ./backend/app
      - /app/node_modules
