export const GET_TODO_LIST = "GET_TODO_LIST";
export type GET_TODO_LIST = typeof GET_TODO_LIST;

export const GET_TODO_LIST_SUCCESS = "GET_TODO_LIST_SUCCESS";
export type GET_TODO_LIST_SUCCESS = typeof GET_TODO_LIST_SUCCESS;

export const GET_TODO = "GET_TODO";
export type GET_TODO = typeof GET_TODO;

export const GET_TODO_SUCCESS = "GET_TODO_ITEM_SUCCESS";
export type GET_TODO_SUCCESS = typeof GET_TODO_SUCCESS;

export const CREATE_TODO = "CREATE_TODO";
export type CREATE_TODO = typeof CREATE_TODO;

export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export type CREATE_TODO_SUCCESS = typeof CREATE_TODO_SUCCESS;

export const DELETE_TODO = "DELETE_TODO";
export type DELETE_TODO = typeof DELETE_TODO;

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export type DELETE_TODO_SUCCESS = typeof DELETE_TODO_SUCCESS;
